#sudo docker run -e URL="jdbc:postgresql://192.168.100.103:5432/software" demo:2.0.0
#sudo docker run -d --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -v /home/juancajca/Documents/postgres-arqui:/var/lib/postresql/data -p 5432:5432 -d postgres
version: "2.4"

services:
  postgres:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - "${VOLUME_LINK}"
  currency-converter:
    image: demo:2.0.0
    ports:
      - "8008:8008"
    restart: always
    environment:
      URL: "${POSTGRES_URL}"
    depends_on:
      - postgres