#sudo docker run -e URL="jdbc:postgresql://192.168.100.103:5432/software" demo:2.0.0
#sudo docker run -d --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -v /home/juancajca/Documents/postgres-arqui:/var/lib/postresql/data -p 5432:5432 -d postgres
version: "2.4"


services:
  postgres:
    image: postgres:15
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - "${VOLUME_LINK}"
    networks:
      - my-network

  currency-converter:
    image: demo:4.0.0
    ports:
      - "8008:8008"
    restart: always
    environment:
      URL: "${POSTGRES_URL}"
    volumes:
      - /home/juanca/Documents/UCB/Arquitectura/Arquitectura-API-Kotlin:/logs/archived/
    depends_on:
      - postgres
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  angular:
#    image: angular-software:3.0.0
    image: angular-software-4.0.0-docker
    restart: always
    ports:
      - "4200:80"
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - currency-converter
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.3.0.0/16
          gateway: 172.3.0.1